// react/solid/Archive.jsx
import * as React from "react";

function ArchiveIcon(props) {
  return <svg viewBox="0 0 20 20" fill="currentColor" {...props}><path d="M4 3a2 2 0 100 4h12a2 2 0 100-4H4z" /><path fillRule="evenodd" d="M3 8h14v7a2 2 0 01-2 2H5a2 2 0 01-2-2V8zm5 3a1 1 0 011-1h2a1 1 0 110 2H9a1 1 0 01-1-1z" clipRule="evenodd" /></svg>;
}

export default ArchiveIcon;

// vue/solid/Archive.js
import { createVNode as _createVNode, openBlock as _openBlock, createBlock as _createBlock } from "vue"

export function render(_ctx, _cache) {
return (_openBlock(), _createBlock("svg", {
  viewBox: "0 0 20 20",
  fill: "currentColor"
}, [
  _createVNode("path", { d: "M4 3a2 2 0 100 4h12a2 2 0 100-4H4z" }),
  _createVNode("path", {
    "fill-rule": "evenodd",
    d: "M3 8h14v7a2 2 0 01-2 2H5a2 2 0 01-2-2V8zm5 3a1 1 0 011-1h2a1 1 0 110 2H9a1 1 0 01-1-1z",
    "clip-rule": "evenodd"
  })
]))
}
